// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlantCfg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from PlantCfg.proto</summary>
  public static partial class PlantCfgReflection {

    #region Descriptor
    /// <summary>File descriptor for PlantCfg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlantCfgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5QbGFudENmZy5wcm90bxIGY29uZmlnIr8BCgtQbGFudENmZ1NldBIvCglw",
            "bGFudGNmZ3MYASADKAsyHC5jb25maWcuUGxhbnRDZmdTZXQuUGxhbnRDZmca",
            "fwoIUGxhbnRDZmcSDAoEbl9pZBgBIAIoBRIOCgZzX25hbWUYAiACKAkSEAoI",
            "bl9yYXJpdHkYAyACKAUSDwoHc19tb2RlbBgEIAIoCRIPCgduX3RpbWVzGAUg",
            "AigFEhIKCm5fcHJvcGVydHkYBiACKAUSDQoFc19kZXMYByACKAlCAkgD"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.PlantCfgSet), global::Config.PlantCfgSet.Parser, new[]{ "Plantcfgs" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Config.PlantCfgSet.Types.PlantCfg), global::Config.PlantCfgSet.Types.PlantCfg.Parser, new[]{ "NId", "SName", "NRarity", "SModel", "NTimes", "NProperty", "SDes" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlantCfgSet : pb::IMessage<PlantCfgSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlantCfgSet> _parser = new pb::MessageParser<PlantCfgSet>(() => new PlantCfgSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlantCfgSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.PlantCfgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlantCfgSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlantCfgSet(PlantCfgSet other) : this() {
      plantcfgs_ = other.plantcfgs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlantCfgSet Clone() {
      return new PlantCfgSet(this);
    }

    /// <summary>Field number for the "plantcfgs" field.</summary>
    public const int PlantcfgsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Config.PlantCfgSet.Types.PlantCfg> _repeated_plantcfgs_codec
        = pb::FieldCodec.ForMessage(10, global::Config.PlantCfgSet.Types.PlantCfg.Parser);
    private readonly pbc::RepeatedField<global::Config.PlantCfgSet.Types.PlantCfg> plantcfgs_ = new pbc::RepeatedField<global::Config.PlantCfgSet.Types.PlantCfg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Config.PlantCfgSet.Types.PlantCfg> Plantcfgs {
      get { return plantcfgs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlantCfgSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlantCfgSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!plantcfgs_.Equals(other.plantcfgs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= plantcfgs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      plantcfgs_.WriteTo(output, _repeated_plantcfgs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      plantcfgs_.WriteTo(ref output, _repeated_plantcfgs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += plantcfgs_.CalculateSize(_repeated_plantcfgs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlantCfgSet other) {
      if (other == null) {
        return;
      }
      plantcfgs_.Add(other.plantcfgs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            plantcfgs_.AddEntriesFrom(input, _repeated_plantcfgs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            plantcfgs_.AddEntriesFrom(ref input, _repeated_plantcfgs_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PlantCfgSet message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class PlantCfg : pb::IMessage<PlantCfg>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<PlantCfg> _parser = new pb::MessageParser<PlantCfg>(() => new PlantCfg());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<PlantCfg> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Config.PlantCfgSet.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PlantCfg() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PlantCfg(PlantCfg other) : this() {
          _hasBits0 = other._hasBits0;
          nId_ = other.nId_;
          sName_ = other.sName_;
          nRarity_ = other.nRarity_;
          sModel_ = other.sModel_;
          nTimes_ = other.nTimes_;
          nProperty_ = other.nProperty_;
          sDes_ = other.sDes_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PlantCfg Clone() {
          return new PlantCfg(this);
        }

        /// <summary>Field number for the "n_id" field.</summary>
        public const int NIdFieldNumber = 1;
        private readonly static int NIdDefaultValue = 0;

        private int nId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int NId {
          get { if ((_hasBits0 & 1) != 0) { return nId_; } else { return NIdDefaultValue; } }
          set {
            _hasBits0 |= 1;
            nId_ = value;
          }
        }
        /// <summary>Gets whether the "n_id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasNId {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "n_id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearNId() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "s_name" field.</summary>
        public const int SNameFieldNumber = 2;
        private readonly static string SNameDefaultValue = "";

        private string sName_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string SName {
          get { return sName_ ?? SNameDefaultValue; }
          set {
            sName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "s_name" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasSName {
          get { return sName_ != null; }
        }
        /// <summary>Clears the value of the "s_name" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearSName() {
          sName_ = null;
        }

        /// <summary>Field number for the "n_rarity" field.</summary>
        public const int NRarityFieldNumber = 3;
        private readonly static int NRarityDefaultValue = 0;

        private int nRarity_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int NRarity {
          get { if ((_hasBits0 & 2) != 0) { return nRarity_; } else { return NRarityDefaultValue; } }
          set {
            _hasBits0 |= 2;
            nRarity_ = value;
          }
        }
        /// <summary>Gets whether the "n_rarity" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasNRarity {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "n_rarity" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearNRarity() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "s_model" field.</summary>
        public const int SModelFieldNumber = 4;
        private readonly static string SModelDefaultValue = "";

        private string sModel_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string SModel {
          get { return sModel_ ?? SModelDefaultValue; }
          set {
            sModel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "s_model" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasSModel {
          get { return sModel_ != null; }
        }
        /// <summary>Clears the value of the "s_model" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearSModel() {
          sModel_ = null;
        }

        /// <summary>Field number for the "n_times" field.</summary>
        public const int NTimesFieldNumber = 5;
        private readonly static int NTimesDefaultValue = 0;

        private int nTimes_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int NTimes {
          get { if ((_hasBits0 & 4) != 0) { return nTimes_; } else { return NTimesDefaultValue; } }
          set {
            _hasBits0 |= 4;
            nTimes_ = value;
          }
        }
        /// <summary>Gets whether the "n_times" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasNTimes {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "n_times" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearNTimes() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "n_property" field.</summary>
        public const int NPropertyFieldNumber = 6;
        private readonly static int NPropertyDefaultValue = 0;

        private int nProperty_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int NProperty {
          get { if ((_hasBits0 & 8) != 0) { return nProperty_; } else { return NPropertyDefaultValue; } }
          set {
            _hasBits0 |= 8;
            nProperty_ = value;
          }
        }
        /// <summary>Gets whether the "n_property" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasNProperty {
          get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "n_property" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearNProperty() {
          _hasBits0 &= ~8;
        }

        /// <summary>Field number for the "s_des" field.</summary>
        public const int SDesFieldNumber = 7;
        private readonly static string SDesDefaultValue = "";

        private string sDes_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string SDes {
          get { return sDes_ ?? SDesDefaultValue; }
          set {
            sDes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "s_des" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool HasSDes {
          get { return sDes_ != null; }
        }
        /// <summary>Clears the value of the "s_des" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearSDes() {
          sDes_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as PlantCfg);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(PlantCfg other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (NId != other.NId) return false;
          if (SName != other.SName) return false;
          if (NRarity != other.NRarity) return false;
          if (SModel != other.SModel) return false;
          if (NTimes != other.NTimes) return false;
          if (NProperty != other.NProperty) return false;
          if (SDes != other.SDes) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (HasNId) hash ^= NId.GetHashCode();
          if (HasSName) hash ^= SName.GetHashCode();
          if (HasNRarity) hash ^= NRarity.GetHashCode();
          if (HasSModel) hash ^= SModel.GetHashCode();
          if (HasNTimes) hash ^= NTimes.GetHashCode();
          if (HasNProperty) hash ^= NProperty.GetHashCode();
          if (HasSDes) hash ^= SDes.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasNId) {
            output.WriteRawTag(8);
            output.WriteInt32(NId);
          }
          if (HasSName) {
            output.WriteRawTag(18);
            output.WriteString(SName);
          }
          if (HasNRarity) {
            output.WriteRawTag(24);
            output.WriteInt32(NRarity);
          }
          if (HasSModel) {
            output.WriteRawTag(34);
            output.WriteString(SModel);
          }
          if (HasNTimes) {
            output.WriteRawTag(40);
            output.WriteInt32(NTimes);
          }
          if (HasNProperty) {
            output.WriteRawTag(48);
            output.WriteInt32(NProperty);
          }
          if (HasSDes) {
            output.WriteRawTag(58);
            output.WriteString(SDes);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasNId) {
            output.WriteRawTag(8);
            output.WriteInt32(NId);
          }
          if (HasSName) {
            output.WriteRawTag(18);
            output.WriteString(SName);
          }
          if (HasNRarity) {
            output.WriteRawTag(24);
            output.WriteInt32(NRarity);
          }
          if (HasSModel) {
            output.WriteRawTag(34);
            output.WriteString(SModel);
          }
          if (HasNTimes) {
            output.WriteRawTag(40);
            output.WriteInt32(NTimes);
          }
          if (HasNProperty) {
            output.WriteRawTag(48);
            output.WriteInt32(NProperty);
          }
          if (HasSDes) {
            output.WriteRawTag(58);
            output.WriteString(SDes);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (HasNId) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NId);
          }
          if (HasSName) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(SName);
          }
          if (HasNRarity) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NRarity);
          }
          if (HasSModel) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(SModel);
          }
          if (HasNTimes) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NTimes);
          }
          if (HasNProperty) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NProperty);
          }
          if (HasSDes) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(SDes);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(PlantCfg other) {
          if (other == null) {
            return;
          }
          if (other.HasNId) {
            NId = other.NId;
          }
          if (other.HasSName) {
            SName = other.SName;
          }
          if (other.HasNRarity) {
            NRarity = other.NRarity;
          }
          if (other.HasSModel) {
            SModel = other.SModel;
          }
          if (other.HasNTimes) {
            NTimes = other.NTimes;
          }
          if (other.HasNProperty) {
            NProperty = other.NProperty;
          }
          if (other.HasSDes) {
            SDes = other.SDes;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                NId = input.ReadInt32();
                break;
              }
              case 18: {
                SName = input.ReadString();
                break;
              }
              case 24: {
                NRarity = input.ReadInt32();
                break;
              }
              case 34: {
                SModel = input.ReadString();
                break;
              }
              case 40: {
                NTimes = input.ReadInt32();
                break;
              }
              case 48: {
                NProperty = input.ReadInt32();
                break;
              }
              case 58: {
                SDes = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                NId = input.ReadInt32();
                break;
              }
              case 18: {
                SName = input.ReadString();
                break;
              }
              case 24: {
                NRarity = input.ReadInt32();
                break;
              }
              case 34: {
                SModel = input.ReadString();
                break;
              }
              case 40: {
                NTimes = input.ReadInt32();
                break;
              }
              case 48: {
                NProperty = input.ReadInt32();
                break;
              }
              case 58: {
                SDes = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
