// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Test {

  /// <summary>Holder for reflection information generated from test2.proto</summary>
  public static partial class Test2Reflection {

    #region Descriptor
    /// <summary>File descriptor for test2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Test2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt0ZXN0Mi5wcm90bxIEdGVzdCIyCgh0ZXN0ZGF0YRIRCgltZXNzYWdlaWQY",
            "ASACKAUSEwoLbWVzc2FnZUluZm8YAiACKAk="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Test.testdata), global::Test.testdata.Parser, new[]{ "Messageid", "MessageInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class testdata : pb::IMessage<testdata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<testdata> _parser = new pb::MessageParser<testdata>(() => new testdata());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<testdata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Test.Test2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public testdata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public testdata(testdata other) : this() {
      _hasBits0 = other._hasBits0;
      messageid_ = other.messageid_;
      messageInfo_ = other.messageInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public testdata Clone() {
      return new testdata(this);
    }

    /// <summary>Field number for the "messageid" field.</summary>
    public const int MessageidFieldNumber = 1;
    private readonly static int MessageidDefaultValue = 0;

    private int messageid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Messageid {
      get { if ((_hasBits0 & 1) != 0) { return messageid_; } else { return MessageidDefaultValue; } }
      set {
        _hasBits0 |= 1;
        messageid_ = value;
      }
    }
    /// <summary>Gets whether the "messageid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMessageid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "messageid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessageid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "messageInfo" field.</summary>
    public const int MessageInfoFieldNumber = 2;
    private readonly static string MessageInfoDefaultValue = "";

    private string messageInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MessageInfo {
      get { return messageInfo_ ?? MessageInfoDefaultValue; }
      set {
        messageInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "messageInfo" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMessageInfo {
      get { return messageInfo_ != null; }
    }
    /// <summary>Clears the value of the "messageInfo" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessageInfo() {
      messageInfo_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as testdata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(testdata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Messageid != other.Messageid) return false;
      if (MessageInfo != other.MessageInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMessageid) hash ^= Messageid.GetHashCode();
      if (HasMessageInfo) hash ^= MessageInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMessageid) {
        output.WriteRawTag(8);
        output.WriteInt32(Messageid);
      }
      if (HasMessageInfo) {
        output.WriteRawTag(18);
        output.WriteString(MessageInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMessageid) {
        output.WriteRawTag(8);
        output.WriteInt32(Messageid);
      }
      if (HasMessageInfo) {
        output.WriteRawTag(18);
        output.WriteString(MessageInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasMessageid) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Messageid);
      }
      if (HasMessageInfo) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(testdata other) {
      if (other == null) {
        return;
      }
      if (other.HasMessageid) {
        Messageid = other.Messageid;
      }
      if (other.HasMessageInfo) {
        MessageInfo = other.MessageInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Messageid = input.ReadInt32();
            break;
          }
          case 18: {
            MessageInfo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Messageid = input.ReadInt32();
            break;
          }
          case 18: {
            MessageInfo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
