// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PlantSeedCfg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Config
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlantSeedCfgSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plantseedcfgs")]
        public global::System.Collections.Generic.List<PlantSeedCfg> Plantseedcfgs { get; } = new global::System.Collections.Generic.List<PlantSeedCfg>();

        [global::ProtoBuf.ProtoMember(2, Name = @"l_crc_code", IsRequired = true)]
        public long LCrcCode { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlantSeedCfg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"n_id", IsRequired = true)]
            public int NId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"s_name", IsRequired = true)]
            public string SName { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"n_rarity", IsRequired = true)]
            public int NRarity { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"s_image", IsRequired = true)]
            public string SImage { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"s_des", IsRequired = true)]
            public string SDes { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"n_plantid", IsRequired = true)]
            public int NPlantid { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
